### ISSUE TITLE
Native updater

### ISSUE THREAD

**Issue by Taekiro** [YunoHost-Apps/nextcloud_ynh#208]
Hi,
It seems that the version 15.0.5 introduce an native update mechanism through nextcloud.example.com/updater (or in settings admin / overview). I didn’t test it (I don't want to break something) but I asked myself if it will interfere with the “normal” way to upgrade with YunoHost.

Salut,
Il semble que la version 15.0.5 introduit un mécanisme intégré d’update via nextcloud.example.com/updater (ou dans les settings admin / overview). Je n’ai pas testé (je veux pas cassé mon install) mais je me demande donc si cela ne va pas interférer avec la façon d’upgrade avec YunoHost.

**Comment by JimboJoe** [comment]
Hi,
Yes, I do think it will interfere. We manage Nextcloud versions in YunoHost packages, because we add specific tuning/code modifications (e.g. for SSO logout, YunoHost tile).

**Comment by Bugsbane** [comment]
Ideally we would handle this with a two part approach:

1. We change the Nextcloud updater URL to one run by nextcloud_ynh, so updates only show as being available in Nextcloud, when there's actually an update compatible with the current version of Yunohost. In other words, the update URL maks a new release, when there's a new release of nextcloud_ynh rather than Nextcloud itself.

2. We modify the "Update" button in Nextcloud to go to the nextcloud_ynh update page instead of using Nextcloud's native updater.

Combining these two, people would only see a Nextcloud update notification when the next update was compatible (and not when it isn't such as NC16 now being incompatible with Yunohost's version of PHP), and when they clicked it, saw a new version available and clicked the "Update" button in Nextcloud, Yunohost would update nextcloud_ynh.
