### ISSUE TITLE
ONLYOFFICE not reachable. Contact your Administrator.

### ISSUE THREAD

**Issue by rocky-III** [YunoHost-Apps/nextcloud_ynh#287]
I´m getting always 
"ONLYOFFICE not reachable. Contact your Administrator."
if I try to use ONLYOFFICE 

https://github.com/nextcloud/documentserver_community/issues/24

**Comment by yekibud** [comment]
@rocky-III Have you tried adding `index.php/` after the `nextcloud` path in the ONLYOFFICE document server setting, e.g. https://<myyunohostdomain.tld>/nextcloud/index.php/apps/documentserver_community/?

**Comment by rocky-III** [comment]
YES YES YES... thanks so much...

 https://<myyunohostdomain.tld>/index.php/apps/documentserver_community/

solved the problem

**Comment by ftoral** [comment]
Thanks @yekibud :+1: 

For those who wants more detailed instructions, the added documentation by @lapineige into the [Yunohost NC app README](https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/README.md), which is currently waiting approval, read it here : 

- [Configure OnlyOffice integration](https://github.com/YunoHost-Apps/nextcloud_ynh/blob/c402cc819b0e247b8a90a432c1fb133f575b6953/README.md#configure-onlyoffice-integration)

**Comment by Bugsbane** [comment]
Has this index.php addition been added to ynh_onlyoffice by default? It seems like something that should be default...

**Comment by lapineige** [comment]
I don't know (and think) that is something that we can change from Yunohost package 🤔

**Comment by Bugsbane** [comment]
It depends how they install it... We can modify ynh_onlyoffice (ie if the user installs it from the Yunohost apps panel) pretty easily. If the user installs from the Nextcloud apps page in their instance, we're pretty much out of luck though.

I guess we could theoretically also modify ynh_nextcloud so that when the user installs apps in Nextcloud that it looks at the names of the requested apps. If any of those have a known Yunohost app, Yunohost installs that instead. 

This could be useful wherever Yunohost specific tweaks were needed...
