### ISSUE TITLE
Public links not working + Nextcloud client (desktop and Android) can't connect to Yunohost Nextcloud server

### ISSUE THREAD

**Issue by croulibri** [YunoHost-Apps/nextcloud_ynh#291]
Hello,
Since last update to Nextcloud 18.0.2, the Nextcloud client ( https://github.com/nextcloud/desktop/ ) on my Windows 10 desktop and also on my Debian desktop can't connect to my Yunohost Nextcloud.

The message is "_Aucune connexion au serveur Nextcloud à l'adresse https://myserver/nextcloud. Erreur inconnue_"

On admin section of Nextcloud I only see the following problems :
```
Il y a quelques avertissements concernant votre configuration.

    MySQL est utilisée comme base de données mais ne supporte pas les caractères codés sur 4 octets. Pour pouvoir manipuler les caractères sur 4 octets (comme les émoticônes) sans problème dans les noms de fichiers ou les commentaires par exemple, il est recommandé d'activer le support 4 octets dans MySQL. Pour plus de détails, lisez la page de documentation à ce sujet

    La configuration du serveur web ne permet pas d'atteindre "/.well-known/caldav". Vous trouverez plus d'informations dans la documentation.
    La configuration du serveur web ne permet pas d'atteindre "/.well-known/carddav". Vous trouverez plus d'informations dans la documentation.
    La base de données a quelques index manquant. L'ajout d'index dans de grandes tables peut prendre un certain temps. Elles ne sont donc pas ajoutées automatiquement. En exécutant "occ db:add-missing-indices", ces index manquants pourront être ajoutés manuellement pendant que l'instance continue de tourner. Une fois les index ajoutés, les requêtes sur ces tables sont généralement beaucoup plus rapides.
        Index "calendarobject_calid_index" manquant dans la table "oc_calendarobjects_props".
        Index "schedulobj_principuri_index" manquant dans la table "oc_schedulingobjects".

```

I have tried to disconnect and try to set up a new connexion, but the Nextcloud client can't find my Yunohost Nextcloud server.
The web access to my Nextcloud woks well.

I am on YunoHost 3.7.0.12 and Nextcloud 

EDIT : I realise that public links are not working anymore as they lead directly to the SSO login and not to the file. So I can't share a file to people that have not an account on my Yunohost server :-(

**Comment by lapineige** [comment]
Related to https://github.com/YunoHost-Apps/nextcloud_ynh/issues/48 ?

**Comment by croulibri** [comment]
I have no idea.
But no Nextcloud client can't access to my Yunohost Nextcloud server (Android and Windows and Debian), no public links are working... :-(

I am rather thinking of an NGINX or a firewall issue.
Am I wrong ?
I have no idea how to investigate further.

Any other people facing this issue after update ?

**Comment by Lysden** [comment]
I confirm having the same problem since the last update - with android client, Ubuntu 19.04 et win 10 client.
I've tested various client version with no luck.
The very few clues I found seemed to lead to a certificate problem.

Client message : "_Le nom d'hôte ne correspondait à aucun des hôtes valides pour ce certificat_".

When I force the trust in the certificate, I have the following error in client log :+1: 
`[OCC::OwncloudSetupWizard::slotSystemProxyLookupDone 	No system proxy set by OS
[OCC::AccessManager::createRequest 	2 "" "https://cloud.[myrootdomain]/status.php" has X-Request-ID "e03886bf-97cb-47f3-82b5-99adbcf6e4bf"
[OCC::AbstractNetworkJob::start 	OCC::CheckServerJob created for "https://cloud.[myrootdomain]" + "status.php" "OCC::OwncloudSetupWizard"
[OCC::AbstractNetworkJob::slotFinished 	Redirecting "GET" QUrl("https://cloud.[myrootdomain]/status.php") QUrl("https://[myrootdomain]/yunohost/sso/?r=aHR0cHM6Ly9jbG91ZC5sYS10YW5uaWVyZS5jb20vc3RhdHVzLnBocA==")
[OCC::AccessManager::createRequest 	2 "" "https://[myrootdomain]/yunohost/sso/?r=aHR0cHM6Ly9jbG91ZC5sYS10YW5uaWVyZS5jb20vc3RhdHVzLnBocA==" has X-Request-ID "e8984d23-ccd1-4ace-aaa6-690a8c368312"
[OCC::Account::slotHandleSslErrors 	"SSL-Errors happened for url  \"https://[myrootdomain]/yunohost/sso/?r=aHR0cHM6Ly9jbG91ZC5sYS10YW5uaWVyZS5jb20vc3RhdHVzLnBocA==\" \tError in  QSslCertificate(\"3\", \"03:40:e3:07:97:e7:ff:b0:b9:e9:02:dd:c9:15:35:08:d1:e6\", \"+eIAjnVO84VdZT4EW+Qkjg==\", \"Let's Encrypt Authority X3\", \"cloud.[myrootdomain]\", QMap((1, \"cloud.[myrootdomain]\")), QDateTime(2020-04-08 07:56:29.000 UTC Qt::UTC), QDateTime(2020-07-07 07:56:29.000 UTC Qt::UTC)) : \"Le nom d'hôte ne correspondait à aucun des hôtes valides pour ce certificat\" ( \"Le nom d'hôte ne correspondait à aucun des hôtes valides pour ce certificat\" ) \n " Certs are known and trusted! This is not an actual error.
[OCC::CheckServerJob::finished 	status.php from server is not valid JSON! "<!DOCTYPE html>\n<html>\n<head>\n  <meta charset=\"utf-8\">\n  <title>Portail YunoHost</title>\n\n  \n  <meta name=\"format-detection\" content=\"telephone=no\" />\n  <meta name=\"viewport\" content=\"width=device-width, height=device-height, initial-scale=1\" />\n\n  \n  <meta name=\"robots\" content=\"noindex, nofollow\">\n\n  \n  <link rel=\"stylesheet\" href=\"assets/css/ynh_portal.css\">\n  <link rel=\"stylesheet\" href=\"assets/themes/default/custom_portal.css\">\n\n  \n  <link rel=\"shortcut icon\" href=\"assets/icons/favicon.ico\">\n  <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"assets/icons/apple-touch-icon-57x57.png\">\n  <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"assets/icons/apple-touch-icon-114x114.png\">\n  <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"assets/icons/apple-touch-icon-72x72.png\">\n  <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"assets/icons/apple-touch-icon-144x144.png\">\n  <link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"assets/icons/apple-touch-icon-60x60.png\">\n  <link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"assets/icons/apple-touch-icon-120x120.png\">\n  <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"assets/icons/apple-touch-icon-76x76.png\">\n  <link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"assets/icons/apple-touch-icon-152x152.png\">\n  <link rel=\"icon\" type=\"image/png\" href=\"assets/icons/favicon-196x196.png\" sizes=\"196x196\">\n  <link rel=\"icon\" type=\"image/png\" href=\"assets/icons/favicon-160x160.png\" sizes=\"160x160\">\n  <link rel=\"icon\" type=\"image/png\" href=\"assets/icons/favicon-96x96.png\" sizes=\"96x96\">\n  <link rel=\"icon\" type=\"image/png\" href=\"assets/icons/favicon-16x16.png\" sizes=\"16x16\">\n  <link rel=\"icon\" type=\"image/png\" href=\"assets/icons/favicon-32x32.png\" sizes=\"32x32\">\n  <meta name=\"msapplication-TileColor\" content=\"#41444f\">\n  <meta name=\"msapplication-TileImage\" content=\"/mstile-144x144.png\">\n</head>\n<body class=\"ynh-user-portal \">\n\n  <div id=\"ynh-logo\" class=\"ynh-logo\">\n    <span class=\"element-invisible\">Yunohost</span>\n  </div>\n\n  <div class=\"content\">\n\n\n    <div class=\"wrapper messages info\">Veuillez vous identifier pour acc\xC3\xA9""der \xC3\xA0 cette page</div>\n<div class=\"ynh-wrapper login\">\n<form class=\"login-form\" name=\"input\" action=\"\" method=\"post\">\n  <div class=\"form-group\">\n    <label class=\"icon icon-user\" for=\"user\"><span class=\"element-invisible\">Nom d\xE2\x80\x99utilisateur</span></label>\n    <input id=\"user\" type=\"text\" name=\"user\" placeholder=\"Nom d\xE2\x80\x99utilisateur\" class=\"form-text\" autofocus required>\n  </div>\n  <div class=\"form-group\">\n    <label class=\"icon icon-lock\" for=\"password\"><span class=\"element-invisible\">Mot de passe</span></label>\n    <input id=\"password\" type=\"password\" name=\"password\" placeholder=\"Mot de passe\" class=\"form-text\" required>\n  </div>\n  <input type=\"submit\" value=\"Connexion\" class=\"btn classic-btn large-btn\">\n</form>\n</div>\n\n  </div>\n\n  \n  <script src=\"assets/js/ynh_portal.js\"></script>\n  <script src=\"assets/themes/default/custom_portal.js\"></script>\n</body>\n</html>\n\n" QUrl("https://[myrootdomain]/yunohost/sso/?r=aHR0cHM6Ly9jbG91ZC5sYS10YW5uaWVyZS5jb20vc3RhdHVzLnBocA==") "la valeur n'est pas autorisée"
[OCC::CheckServerJob::finished 	status.php returns:  QJsonDocument()   QNetworkReply::NoError  Reply:  QNetworkReplyHttpImpl(0x55c58ba1f290)
[OCC::CheckServerJob::finished 	No proper answer on  QUrl("https://[myrootdomain]/yunohost/sso/?r=aHR0cHM6Ly9jbG91ZC5sYS10YW5uaWVyZS5jb20vc3RhdHVzLnBocA==")
[OCC::AccessManager::createRequest 	2 "" "https://cloud.[myrootdomain]" has X-Request-ID "b0b92eac-51e5-4dff-943d-8345f7362b40"
[OCC::AbstractNetworkJob::start 	OCC::SimpleNetworkJob created for "https://cloud.[myrootdomain]" + "" "OCC::Account"
[OCC::AbstractNetworkJob::slotFinished 	Redirecting "GET" QUrl("https://cloud.[myrootdomain]") QUrl("https://[myrootdomain]/yunohost/sso/?r=aHR0cHM6Ly9jbG91ZC5sYS10YW5uaWVyZS5jb20vaW5kZXgucGhw")
[OCC::AccessManager::createRequest 	2 "" "https://[myrootdomain]/yunohost/sso/?r=aHR0cHM6Ly9jbG91ZC5sYS10YW5uaWVyZS5jb20vaW5kZXgucGhw" has X-Request-ID "abecd48b-f63b-480b-94e3-282f0054f972"
[OCC::AccessManager::createRequest 	2 "" "https://cloud.[myrootdomain]/status.php" has X-Request-ID "0144107a-ca24-476c-a74d-9a99c7f1c66b"
[OCC::AbstractNetworkJob::start 	OCC::CheckServerJob created for "https://cloud.[myrootdomain]" + "status.php" "OCC::OwncloudSetupWizard"
[OCC::AbstractNetworkJob::slotFinished 	Redirecting "GET" QUrl("https://cloud.[myrootdomain]/status.php") QUrl("https://[myrootdomain]/yunohost/sso/?r=aHR0cHM6Ly9jbG91ZC5sYS10YW5uaWVyZS5jb20vc3RhdHVzLnBocA==")
[OCC::AccessManager::createRequest 	2 "" "https://[myrootdomain]/yunohost/sso/?r=aHR0cHM6Ly9jbG91ZC5sYS10YW5uaWVyZS5jb20vc3RhdHVzLnBocA==" has X-Request-ID "a055d589-ce3e-4c01-8cfe-8328f87f0efd"
[OCC::CheckServerJob::finished 	status.php from server is not valid JSON! "<!DOCTYPE html>\n<html>\n<head>\n  <meta charset=\"utf-8\">\n  <title>Portail YunoHost</title>\n\n  \n  <meta name=\"format-detection\" content=\"telephone=no\" />\n  <meta name=\"viewport\" content=\"width=device-width, height=device-height, initial-scale=1\" />\n\n  \n  <meta name=\"robots\" content=\"noindex, nofollow\">\n\n  \n  <link rel=\"stylesheet\" href=\"assets/css/ynh_portal.css\">\n  <link rel=\"stylesheet\" href=\"assets/themes/default/custom_portal.css\">\n\n  \n  <link rel=\"shortcut icon\" href=\"assets/icons/favicon.ico\">\n  <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"assets/icons/apple-touch-icon-57x57.png\">\n  <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"assets/icons/apple-touch-icon-114x114.png\">\n  <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"assets/icons/apple-touch-icon-72x72.png\">\n  <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"assets/icons/apple-touch-icon-144x144.png\">\n  <link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"assets/icons/apple-touch-icon-60x60.png\">\n  <link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"assets/icons/apple-touch-icon-120x120.png\">\n  <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"assets/icons/apple-touch-icon-76x76.png\">\n  <link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"assets/icons/apple-touch-icon-152x152.png\">\n  <link rel=\"icon\" type=\"image/png\" href=\"assets/icons/favicon-196x196.png\" sizes=\"196x196\">\n  <link rel=\"icon\" type=\"image/png\" href=\"assets/icons/favicon-160x160.png\" sizes=\"160x160\">\n  <link rel=\"icon\" type=\"image/png\" href=\"assets/icons/favicon-96x96.png\" sizes=\"96x96\">\n  <link rel=\"icon\" type=\"image/png\" href=\"assets/icons/favicon-16x16.png\" sizes=\"16x16\">\n  <link rel=\"icon\" type=\"image/png\" href=\"assets/icons/favicon-32x32.png\" sizes=\"32x32\">\n  <meta name=\"msapplication-TileColor\" content=\"#41444f\">\n  <meta name=\"msapplication-TileImage\" content=\"/mstile-144x144.png\">\n</head>\n<body class=\"ynh-user-portal \">\n\n  <div id=\"ynh-logo\" class=\"ynh-logo\">\n    <span class=\"element-invisible\">Yunohost</span>\n  </div>\n\n  <div class=\"content\">\n\n\n    <div class=\"wrapper messages info\">Veuillez vous identifier pour acc\xC3\xA9""der \xC3\xA0 cette page</div>\n<div class=\"ynh-wrapper login\">\n<form class=\"login-form\" name=\"input\" action=\"\" method=\"post\">\n  <div class=\"form-group\">\n    <label class=\"icon icon-user\" for=\"user\"><span class=\"element-invisible\">Nom d\xE2\x80\x99utilisateur</span></label>\n    <input id=\"user\" type=\"text\" name=\"user\" placeholder=\"Nom d\xE2\x80\x99utilisateur\" class=\"form-text\" autofocus required>\n  </div>\n  <div class=\"form-group\">\n    <label class=\"icon icon-lock\" for=\"password\"><span class=\"element-invisible\">Mot de passe</span></label>\n    <input id=\"password\" type=\"password\" name=\"password\" placeholder=\"Mot de passe\" class=\"form-text\" required>\n  </div>\n  <input type=\"submit\" value=\"Connexion\" class=\"btn classic-btn large-btn\">\n</form>\n</div>\n\n  </div>\n\n  \n  <script src=\"assets/js/ynh_portal.js\"></script>\n  <script src=\"assets/themes/default/custom_portal.js\"></script>\n</body>\n</html>\n\n" QUrl("https://[myrootdomain]/yunohost/sso/?r=aHR0cHM6Ly9jbG91ZC5sYS10YW5uaWVyZS5jb20vc3RhdHVzLnBocA==") "la valeur n'est pas autorisée"
[OCC::CheckServerJob::finished 	status.php returns:  QJsonDocument()   QNetworkReply::NoError  Reply:  QNetworkReplyHttpImpl(0x55c58b035cb0)
[OCC::CheckServerJob::finished 	No proper answer on  QUrl("https://[myrootdomain]/yunohost/sso/?r=aHR0cHM6Ly9jbG91ZC5sYS10YW5uaWVyZS5jb20vc3RhdHVzLnBocA==")`

I too think about a NGINX problem, but where ?

**Comment by Lysden** [comment]
@lapineige no it's not. I have performed the necessary update with no improvement on the connection problem.

**Comment by alexAubin** [comment]
@croulibri @Lysden 
>EDIT : I realise that public links are not working anymore as they lead directly to the SSO login and  not to the file. So I can't share a file to people that have not an account on my Yunohost server :-(
>[...]
>But no Nextcloud client can't access to my Yunohost Nextcloud server (Android and Windows and Debian), no public links are working... :-(

Could it be that you removed the Nextcloud permission from the "Visitors" group in the permission management screen ?

**Comment by croulibri** [comment]
I have never touch the "visitors" group
The group exist but there is no users inside

**Comment by alexAubin** [comment]
Alright, though can you just confirm / doublecheck that if you [go to the permission interface](https://yunohost.org/images/button_to_go_to_permission_interface.png), you see Nextcloud allowed for visitors ?

**Comment by croulibri** [comment]
No, Nextcloud was not allowed for visitors. Should I allow it ?

**Comment by croulibri** [comment]
If I allow, public links are working again 🎆 
But I still can't connect with Nextcloud client. On ly desktop, I get 
![image](https://user-images.githubusercontent.com/18677287/78800069-4e6f8c80-79bb-11ea-956a-c44c3f021830.png)

**Comment by alexAubin** [comment]
Hmokay that doesn't really explain why it didn't get allowed automatically during the upgrade / migration but okay x_X We shall keep an eye on that kind of thing

**Comment by Lysden** [comment]
> Could it be that you removed the Nextcloud permission from the "Visitors" group in the permission management screen ?

In my case, I've recently modified these parameters and probably this one too. Everything is back too normal since the permission is set to visitor. Thanks!
