### ISSUE TITLE
Unable to share folders with a public link

### ISSUE THREAD

**Issue by Krands** [YunoHost-Apps/nextcloud_ynh#5]
Hi,

I've been in an Education Center to get a job, and instead of sharing via gDrive or OneDrive, I'd like to show to my group that you could use something else. So I decided to share with my NextCloud app on Yunohost, however, for some reason, I can't.

It says

> Sharing is not allowed.

I checked those things:

* [x] My NextCloud app has public access,
* [x] I allowed the use of the Share API,
* [x] I set permissions `chmod` and `chown` open enough so users with the link can see the files/folders.

At some point, I need to go deeper, but I don't know what to do. I checked everything I am aware of.

What am I missing?

:beers:

[`Link to the Yunohost topic`](https://forum.yunohost.org/t/nextcloud-unable-to-share-folders-with-a-public-link/1966)

**Comment by jeromelebleu** [comment]
Hi Krands, where does this message appear please? I've tried on my instance and I don't have any issue... I'm just clicking on the share icon of the file or the folder that I want to share and check the *Share link*.

**Comment by Krands** [comment]
Hi,

Right there : 
![screenshot](https://cloud.githubusercontent.com/assets/6728594/19207473/9722f058-8cf1-11e6-86e1-1dcbbd502706.png)

**Comment by jeromelebleu** [comment]
Is it a new Nextcloud installation or a migration from ownCloud?

If it's a new one, did you check the "Access the users home folder from Nextcloud?" at installation? It'll in that case use the *External storage support* application to access your files located in your home folder - which I think it's the case due to the icon of the folder. I've tested that case and you'll have to check *Enable sharing* (*Permettre le partage* in French) in *Admin* (*Administration* in French) > *External storages* (*Stockages externes* in French) by clicking on the wheel icon of the *Home* share:

![Enable sharing - screenshot](https://cloud.githubusercontent.com/assets/3597194/19213681/a2d8be74-8d72-11e6-9fd5-26121527c2b5.png)

**Comment by Krands** [comment]
Ha! That's what I was missing! Thank you!

It's a "fresh" install.
(I didn't actually know that one)

**Comment by jeromelebleu** [comment]
Great! :) Do you think that sharing should be activated by default?

**Comment by Krands** [comment]
It would be nice, because it's another parameter to think about when you think about sharing, as previously:
>* [x] My NextCloud app has public access,
* [x] I allowed the use of the Share API,
* [x] I set permissions `chmod` and `chown` open enough so users with the link can see the files/folders.

Maybe asking during the installation if the user will want to share would be nice:
`Do you want to share your folders within your NextCloud instance?`

This would help, I guess. It's about UX.

**Comment by jeromelebleu** [comment]
Okay, thanks for your view and this report. I've enabled the sharing by default with https://github.com/YunoHost-Apps/nextcloud_ynh/commit/fa25e5005280e531d04249cb19fbbfe6804b38ee.
