### ISSUE TITLE
Update package to 12.0.4

### ISSUE THREAD

**Issue by eeeple** [YunoHost-Apps/nextcloud_ynh#75]
Update is possible through command line but not available in the nextcloud admin panel.
`sudo -u nextcloud php /var/www/nextcloud/updater/updater.phar -vv`

**Comment by Chklang** [comment]
Thanks for the command to update :)

**Comment by maniackcrudelis** [comment]
It's really a bad idea to update your nextcloud like that.
It's for a good reason that we forbid the upgrade from nextcloud admin interface.

Nextcloud is really sensitive about its upgrade, when you will upgrade your nextcloud package, if you are on an upper version than the one the package will installed, your nextcloud will be broken down.

Instead of doing that, and risk your nextcloud, it's far more interesting to upgrade the package and make a pull request. Like that, you will not risking your nextcloud, and everyone will profit of your contribution.
