### ISSUE TITLE
Nextcloud 30

### ISSUE THREAD

**Issue by VOGUK** [YunoHost-Apps/nextcloud_ynh#754]
Hi there, I absolutly love Nextcloud on Yunohost and use it every day, several times a day, so first of all, thank you for your hard work in making it available to us on this platform. I was wondering whether you could let us know when Nextcloud 30 will be availble on Yunohost? Thank you again for your hard work, it's really appreciated!!! :)

**Comment by ericgaspar** [comment]
Nextcloud 30.0.2 is available right now
`sudo yunohost app upgrade nextcloud -u https://github.com/YunoHost-Apps/nextcloud_ynh/tree/testing`

**Comment by VOGUK** [comment]
I notice it says "testing" in the command line. When will it ready to update from the Yunohost GUI? :)

**Comment by alexAubin** [comment]
It will be ready when it is deemed ready ... This is a community project, we don't provide timeline, we know people want this stuff (and underestimate that having brand-new-stuff is overrated compared to having stuff-not-that-old-but-which-works), and people asking "when will X be released" just makes our eyes raise to the sky. If you want to speed things up, help by testing the new version and providing feedback about what doesn't work, otherwise just be patient ...
